### ISSUE TITLE
Global CSS cannot be imported from within node_modules.

### ISSUE THREAD

**Issue by xiqi** [chrisrzhou/react-wordcloud#41]
I got this error after installing this package:
```
Failed to compile
./node_modules/tippy.js/animations/scale.css
Global CSS cannot be imported from within node_modules.
Read more: https://err.sh/next.js/css-npm
Location: node_modules/react-wordcloud/dist/index.module.js #
```
Not quite sure how to fix it. Can you please help taking a look?

Thank you for the work!

**Comment by chrisrzhou** [comment]
I believe I might have screwed up something with the build that doesn't account for all scenarios. Let me reproduce this over the weekend.

It would be tremendously helpful if you can have a Github repo or Codesandbox reproducing this problem that I can clone and test.

Thank you and sorry for the inconvenience. Please use v1.1.1 for now to be unblocked.

**Comment by xiqi** [comment]
Hi Chris,

Sorry about the delay in response!

Here is a repo for you to see a reproduction: https://github.com/xiqi/react-wordcloud-debug

It's using Next.js, simple run `yarn install && yarn run dev` and then open `localhost:3000`

I think importing CSS files from tippy.js is causing this issue:
https://github.com/chrisrzhou/react-wordcloud/blob/d55961059ea65351972b36960b7024e3e61e7297/src/index.js#L1

**Comment by ghost** [comment]
I have a similar problem on the same platform (```next@9.3.5```).
If I try to import a component which includes ```react-workcloud```, I receive this exception:
```
.tippy-box[data-animation=fade][data-state=hidden]{opacity:0}[data-tippy-root]{max-width:calc(100vw - 10px)}.tippy-box{position:relative;background-color:#333;color:#fff;border-radius:4px;font-size:14px;line-height:1.4;outline:0;transition-property:transform,visibility,opacity}.tippy-box[data-placement^=top]>.tippy-arrow{bottom:0}.tippy-box[data-placement^=top]>.tippy-arrow:before{bottom:-7px;left:0;border-width:8px 8px 0;border-top-color:initial;transform-origin:center top}.tippy-box[data-placement^=bottom]>.tippy-arrow{top:0}.tippy-box[data-placement^=bottom]>.tippy-arrow:before{top:-7px;left:0;border-width:0 8px 8px;border-bottom-color:initial;transform-origin:center bottom}.tippy-box[data-placement^=left]>.tippy-arrow{right:0}.tippy-box[data-placement^=left]>.tippy-arrow:before{border-width:8px 0 8px 8px;border-left-color:initial;right:-7px;transform-origin:center left}.tippy-box[data

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1072:16)
    at Module._compile (internal/modules/cjs/loader.js:1122:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Volumes/DATI/Professionale/Progetti/Luca Cattide/LC/Sito/Sviluppo/next/front-end/node_modules/react-wordcloud/dist/index.js:7:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.react-wordcloud (/Volumes/DATI/Professionale/Progetti/Luca Cattide/LC/Sito/Sviluppo/next/front-end/.next/server/static/development/pages/about/[lang].js:6445:18)
    at __webpack_require__ (/Volumes/DATI/Professionale/Progetti/Luca Cattide/LC/Sito/Sviluppo/next/front-end/.next/server/static/development/pages/about/[lang].js:29:31)
    at Module../components/about/TagCloud.js (/Volumes/DATI/Professionale/Progetti/Luca Cattide/LC/Sito/Sviluppo/next/front-end/.next/server/static/development/pages/about/[lang].js:3898:73)
    at __webpack_require__ (/Volumes/DATI/Professionale/Progetti/Luca Cattide/LC/Sito/Sviluppo/next/front-end/.next/server/static/development/pages/about/[lang].js:29:31)
    at Module../pages/about/[lang].js (/Volumes/DATI/Professionale/Progetti/Luca Cattide/LC/Sito/Sviluppo/next/front-end/.next/server/static/development/pages/about/[lang].js:6022:85)
    at __webpack_require__ (/Volumes/DATI/Professionale/Progetti/Luca Cattide/LC/Sito/Sviluppo/next/front-end/.next/server/static/development/pages/about/[lang].js:29:31)
    at Object.5 (/Volumes/DATI/Professionale/Progetti/Luca Cattide/LC/Sito/Sviluppo/next/front-end/.next/server/static/development/pages/about/[lang].js:6301:18)
    at __webpack_require__ (/Volumes/DATI/Professionale/Progetti/Luca Cattide/LC/Sito/Sviluppo/next/front-end/.next/server/static/development/pages/about/[lang].js:29:31)
```

**Comment by chrisrzhou** [comment]
Hey guys, this issue seems specific to `next`.  Although, ideally I should decouple the CSS from the JS package and have users explicitly import the CSS file.  However, since the version has been shipped with included CSS in the past, I want to avoid introducing breaking changes just because of this.

I've never used `next` but after 30min of digging, I found out how to fix this thanks to your repro @xiqi.  Here's the fix:
- Issue: https://github.com/aws-amplify/amplify-js/issues/3854#issuecomment-554200567

The `next.config.js` that fixes it is:
```js
const withCSS = require('@zeit/next-css');

global.navigator = () => null;

if (typeof require !== 'undefined') {
  require.extensions['.less'] = () => {};
  require.extensions['.css'] = file => {};
}

module.exports = withCSS({});
```

It seems that the person who filed the issue has asked for more formal support of CSS by default in an RFC, but hopefully this is a short-term fix for `next`-related builds.  Let me know if the issue persists and reopen the issue.

**Comment by suino** [comment]
Hi, I have a similar problem on the same platform (I tried next@9.3.5 and next@9.3.7).
This fix (https://github.com/chrisrzhou/react-wordcloud/issues/41#issuecomment-616985372) is good for `yarn run dev`.
But I got same problem again when I run `yarn run build` for deployment.
Do you have any solution?

Thank you for nice library!

```sh
$ yarn run build
...
Warning: Built-in CSS support is being disabled due to custom CSS configuration being detected.
See here for more info: https://err.sh/next.js/built-in-css-disabled

Creating an optimized production build  

Compiled successfully.

> Build error occurred
/Users/***/node_modules/tippy.js/dist/tippy.css:1
.tippy-box[data-animation=fade][data-state=hidden]{opacity:0}[data-tippy-root]{max-width:calc(100vw - 10px)}.tippy-box{position:relative;background-color:#333;color:#fff;border-radius:4px;font-size:14px;line-height:1.4;outline:0;transition-property:transform,visibility,opacity}.tippy-box[data-placement^=top]>.tippy-arrow{bottom:0}.tippy-box[data-placement^=top]>.tippy-arrow:before{bottom:-7px;left:0;border-width:8px 8px 0;border-top-color:initial;transform-origin:center top}.tippy-box[data-placement^=bottom]>.tippy-arrow{top:0}.tippy-box[data-placement^=bottom]>.tippy-arrow:before{top:-7px;left:0;border-width:0 8px 8px;border-bottom-color:initial;transform-origin:center bottom}.tippy-box[data-placement^=left]>.tippy-arrow{right:0}.tippy-box[data-placement^=left]>.tippy-arrow:before{border-width:8px 0 8px 8px;border-left-color:initial;right:-7px;transform-origin:center left}.tippy-box[data-placement^=right]>.tippy-arrow{left:0}.tippy-box[data-placement^=right]>.tippy-arrow:before{left:-7px;border-width:8px 8px 8px 0;border-right-color:initial;transform-origin:center right}.tippy-box[data-inertia][data-state=visible]{transition-timing-function:cubic-bezier(.54,1.5,.38,1.11)}.tippy-arrow{width:16px;height:16px;color:#333}.tippy-arrow:before{content:"";position:absolute;border-color:transparent;border-style:solid}.tippy-content{position:relative;padding:5px 9px;z-index:1}
^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1063:16)
    at Module._compile (internal/modules/cjs/loader.js:1111:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/***/node_modules/react-wordcloud/dist/index.js:7:1)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10) {
  type: 'SyntaxError'
}
error Command failed with exit code 1.
```

**Comment by chrisrzhou** [comment]
Hi @suino, I'm not familiar with `next`, so can anyone on this issue confirm if there is a similar fix for `next` builds or they are stuck here as well?  If there are no alternatives, I might split up the CSS file in the next minor release.

**Comment by chrisrzhou** [comment]
Hi @suino, I'm not familiar with `next`, so can anyone on this issue confirm if there is a similar fix for `next` builds or they are stuck here as well?  If there are no alternatives, I might split up the CSS file in the next minor release.

cc @lucacattide

**Comment by suino** [comment]
Thank you. I want to know others' results too.
Though I tried various `next.config.js` settings and a few versions from`next@9.1.0` to `next@9.3.7`, none of them worked well.
I think it's not so easy but I'm very happy if you split up the CSS file.

**Comment by bfeister** [comment]
@chrisrzhou thanks for this, spent half a day on it and was **super puzzled**, this fixed it for me

**Comment by bfeister** [comment]
Actually, I take that back, it's broken for me @chrisrzhou... Works when I run `NODE_ENV=development next dev -p 8025` but breaks when I run `next build`, same as what @suino reported above ☝️
